spring.application.name=backend

# Desativa a configuração automática de banco relacional/JPA, pois o projeto utiliza arquivos JSON para persistência dos dados.
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration